export const KEY_AUTH_TOKEN = "KEY_AUTH_TOKEN" 
export const KEY_PAYMENT_METHOD = "KEY_PAYMENT_METHOD" 

export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const UPDATE_SHIPPING_SUCCESS = "UPDATE_SHIPPING_SUCCESS"
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"

export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const POST_PRODUCT_REVIEW_SUCCESS = "POST_PRODUCT_REVIEW_SUCCESS"

export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"

export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS"